development:
  adapter: postgresql
  encoding: unicode
  database: nessie_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nessie_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: nessie_production
  pool: 5
  username: postgres
  password:
